name: Java CI
'on':
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test
        run: mvn test
        
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Lint job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'

        
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=salilsrivastava_epoch_java_app -Dsonar.organization=salilsrivastava -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
